In [1]:
import numpy as np
from scipy import signal

img = np.array([[111, 112, 113, 114, 115, 114, 113, 112, 111, 110],
                [110, 111, 112, 113, 114, 115, 114, 113, 112, 111],
                [109, 110, 111, 112, 113, 114, 115, 114, 113, 112],
                [108, 109, 110, 111, 112, 113, 114, 115, 114, 113],
                [107, 108, 109, 110, 111, 112, 113, 114, 115, 114]])
tmp = np.array([[1 / 9, 1 / 9, 1 / 9],
                [1 / 9, 1 / 9, 1 / 9],
                [1 / 9, 1 / 9, 1 / 9]])
# convolve2d 二维卷积运算，等价于旋转180度的模板运算
img1 = signal.convolve2d(img, np.rot90(tmp, 2), mode='same')
img2 = signal.convolve2d(img1, np.rot90(tmp, 2), mode='same')
img3 = img2
for i in range(1000):
    img3 = signal.convolve2d(img3, np.rot90(tmp, 2), mode='same')

In [2]:
import numpy as np
from scipy import signal

img = np.array([[111, 112, 113, 114, 115, 114, 113, 112, 111, 110],
                [110, 111, 112, 113, 114, 115, 114, 113, 112, 111],
                [109, 110, 111, 112, 113, 114, 115, 114, 113, 112],
                [108, 109, 110, 111, 112, 113, 114, 115, 114, 113],
                [107, 108, 109, 110, 111, 112, 113, 114, 115, 114]])
tmp = np.array([[0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [1, 0, 0, 0, 0], ])

img1 = np.around(signal.convolve2d(img, np.rot90(tmp, 2), mode='same'))

In [3]:
#DCT
from math import sqrt, cos


def dct_trans(img):
    def alpha(u, X):
        if u == 0:
            return sqrt(1 / X)
        elif u <= X - 1:
            return sqrt(2 / X)
        else:
            raise TypeError

    def cos_mat(u, v, X, Y):
        mat = np.ones([X, Y])
        for x in range(X):
            for y in range(Y):
                # print(cos(np.pi * (2 * x + 1) * u / 2 / X))
                mat[x][y] = cos(np.pi * (2 * x + 1) * u / 2 / X) * cos(np.pi * (2 * y + 1) * v / 2 / Y)
        return mat

    [X, Y] = img.shape
    mat = np.ones([X, Y])
    for u in range(X):
        for v in range(Y):
            a_u = alpha(u, X)
            a_v = alpha(v, Y)
            cos_XY = cos_mat(u, v, X, Y)
            mat[u][v] = a_u * a_v * np.sum(np.multiply(img, cos_XY))
    return mat


img = np.array([[1, 2, 3, 4],
                [5, 5, 5, 5],
                [6, 6, 6, 6],
                [7, 7, 7, 7]])

# 8个格子
dct = dct_trans(img)
print(dct)

[[ 2.05000000e+01 -1.11522125e+00 -9.42055475e-16 -7.92563339e-02]
 [-6.42072944e+00 -1.45710678e+00  3.33066907e-16 -1.03553391e-01]
 [-1.50000000e+00 -1.11522125e+00  0.00000000e+00 -7.92563339e-02]
 [-1.12881949e+00 -6.03553391e-01  0.00000000e+00 -4.28932188e-02]]


In [2]:
img = np.ones([124, 325])
tmp = np.ones([7, 9])

img1 = np.around(signal.convolve2d(img, np.rot90(tmp, 2), mode='full'))
img2 = np.around(signal.convolve2d(img, np.rot90(tmp, 2), mode='same'))
img3 = np.around(signal.convolve2d(img, np.rot90(tmp, 2), mode='valid'))
print('full: {}, same: {}, valid: {}'.format(img1.shape, img2.shape, img3.shape))

full: (130, 333), same: (124, 325), valid: (118, 317)


In [8]:
# 题目说的是卷积运算，不是模板运算

I = np.asarray([[0, 1, -1], [2, 1, 0], [0, 3, -1]])
f_x = np.asarray([[0, 0, 0], [-1, 0, 1], [0, 0, 0]])
f_y = np.asarray([[0, 1, 0], [0, 1, 0], [0, 1, 0]])

g1 = signal.convolve2d(signal.convolve2d(I, f_x, 'same'), f_y, 'same')
g2 = signal.convolve2d(I, signal.convolve2d(f_x, f_y, 'same'), 'same')

print(g1)
print()
print(g2)

print("滤波器的作用是求水平方向的导数。")

[[-2  3  2]
 [-5  4  5]
 [-4  3  4]]

[[-2  3  2]
 [-5  4  5]
 [-4  3  4]]
